### PR TITLE
Redo switching power supply

### LINKED ISSUE #8: LDO to reduce switch noise on negative 5.5V supply
Use a modern low dropout regulator with adjustable output to produce, e.g. -5.3V to maintain +/-5 range while getting rid of noise

### LINKED ISSUE #18: Replace power regulation circuitry, remove translation
## LTC3426 Issues
We use a whole flyback converter to add 0.5V to the incoming 5V rail, so we have something regulate down for the digital and analog LDOs. 

## TPS60403  (switched cap inverter) Issues
Maximal Vin for TPS60403  is 5.2V, but if schematic is correct, the boost converter makes 5.5V at vin:

image

It also only makes 60mA. The negative rail is only use on Ain and Aout amps, but its still pretty pathetic. 

## LDO issues
Following the jacked switching stages above, we then linear-regulate again to make clean +/-5V. But this requires that we use R2R IO opamps to get true +/-5V at inputs and outputs. Further, for some reason, we make a 5V digital rail that so that we can use 5V logic level ADCs and DACs that we level shift back into 3.3V for the FPGA....

**This is me:**
image

**This is this circuit:**
image

## Solution
- Single bi-polar boost/inverting regulator making +/- 6V or so
- Make +/-5.5V using two LDOs (now our opamps have some head room)
- Remove digital LDOs
- Use ADCs and DACs with 3.3 volt logic levels and remove all the translation ICs

### LINKED ISSUE #19: DAC_REF unconnected
These pins are undriven as far as I can see. 

image

### LINKED ISSUE #24: Remove jumpers in ADC buffer operating point network
There are jumpers that allow the buffer amp and operating point shifting network to be skipped. This invites misuse and there is no way to tell if its been done in software. These should be removed.

### PR DESCRIPTION
**Pull request by jonnew**
- Replace boost converter and charge pump inverter with a dual supply based around the LT3471
- Fix feedback network on 5VA0`
- The schottky diode and inductor footprints need to be verified
- There is a recommended layout for the LT3471 on page 10 of the [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/3471fb.pdf)
- The LTspice circuit shows the switching regulators operation
- Fixes #18 
- Fixes #24 
- Fixes #19
- Fixes #8

### CODE REVIEW

**Comment by jonnew** [comment]
The kicad version was bumped to 8.0 which has a lot of nice layout tools. Its worth upgrading.

**Comment by filcarv** [comment]
@jonnew , what's the KiCAD version you've used to edit the files?

**Comment by jonnew** [comment]
> The kicad version was bumped to 8.0 which has a lot of nice layout tools. Its worth upgrading.

See above comment

**Comment by jonnew** [comment]
I realized that we may want to bump the analog rails by a couple hundred millivolts to give the output and input amplifiers a bit of headroom for 5V. These LDOs have 150 mV drop out at full load so making -5.2V to 5.2V for the analog rails should not be a problem. Should I proceed with that?

**Comment by filcarv** [comment]
I would suggest yes, it will give full-scale to the device.
Nevertheless, there might be an issue.
ADcs and DACs are using the +5VD supply, which is not correct, they should use the +5VA because +5VD are going to noisy devices. If you increase the +5VA to 5.2V (which I think makes very sense) the ADC (that uses the supply +5VA as reference) will have a wrong reference equal to 5.2V. Probably the best would be to change the ADC to one that have external reference (the ADC_REF already exists the circuit, that can be tuned to 5V).
If this makes sense, you can suggest a new ADC (maybe already from the list of replacements?) with external reference and we can replace the ADCs on Lisbon end.
let me know what you think, @jonnew .

**Comment by jonnew** [comment]
Reference options:

MCP4921T-E/MS
- Dedicated reference input with optional x2 gain. 
- Could use 2.5V reference

ADC121S021
- Power supply is reference, no other option

After looking around for a while, I think the changes required to get a new DAC and ADC are way more work than just dealing with a 5.2V reference voltage.  Its weird but allowed by both chips and amounts to a different voltage conversion equation in the software.  The true input span of the system will be 12-bits spread over -5.2V to 5.2V. It will be advertised as -5 to 5V IO.

**Comment by jonnew** [comment]
Ive made this changes and in doing so found lots of issues with the design. They are too numerous for me to write here but the big take homes

- Power supply symbols are special global labels in kicad. They are to be used instead of manual global labels for power supply nets
- Proper symbols will aid ERC. These symbols don't have Pin types defined so we are really winging it here
- There are lots of off grid parts which can lead to spurious connections. 
image

**Comment by jonnew** [comment]
We need to to go back to the commit with the original import and check for sanity of these connections. Its possible that these issues arose when i was redoing the power supplies and the global names propagated to nets they should not have. 

@aacuevas is looking into it.

**Comment by jonnew** [comment]
@aacuevas suggested yet another option: run the ADC and DAC off of 3.3V instead of 5. Scale the +/-5V into 0-3.3V. Get rid of logic level translators.

In anycase, the jumpers that change the input amps into a follower that passes -voltages needs to be removed. It makes no sense because the ADCs are monopolar and this invites misuse.

**Comment by jonnew** [comment]
@aacuevas If you can give this thing a look over I would really appreciate it.

**Comment by aacuevas** [comment]
The level converter and hdmi output for TTLout (in page 1, same page as the regulators) is still using the old +5VD net instead of the new +5V used for all digital lines. Apart from that, seems ok to me.

BTW, to leave it documented, we have decided against the option of running the ADC/DACs at 3v3 as that would be mixing supplies in a way that could cause unwanted situations, so the full range for the ADC/DACs is actually +/-5.2V, but we use and advertise a +/5V range (the extra 0.4V are left as safety margins, which is not an uncommon property to have)

**Pull request merged**
